# Generated by Django 3.1.3 on 2020-11-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Related_Movie',
        ),
    ]
